sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
before_script:
- echo 'America/New_York' | sudo tee /etc/timezone
- sudo dpkg-reconfigure --frontend noninteractive tzdata
script:
- npm test
- npm run coveralls